[Plugins]
kinetic_scaleEnabled=true
kinetic_maximizeEnabled=true
kinetic_squashEnabled=true
kinetic_fadingpopupsEnabled=true

ling_scaleEnabled=false
ling_squashEnabled=false
ling_popupsEnabled=false
